---
# Set default variables
- include: set-default-variables.yml

- name: get my public IP
  ipify_facts:

- name: Ensure the APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Streisand common packages
  apt:
    name: "{{ item }}"
  with_items: "{{ streisand_common_packages }}"

- name: Copy the unattended-upgrades templates to enable automatic security updates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "20auto-upgrades",       dest: "/etc/apt/apt.conf.d" }
    - { src: "50unattended-upgrades", dest: "/etc/apt/apt.conf.d" }
